### ISSUE TITLE
关于预渲染

### ISSUE THREAD

**Issue by wangtao666** [Jhaidi/SSR#1]
请问你是怎么做预渲染的？我这里增加了meta标签固定屏幕的显示大小，页面先是没固定到后面meta标签生效，其中有一个变化过程，用户全都可以看到，请问有什么办法让他渲染好了再呈现，谢谢！

**Comment by Jinx-1120** [comment]
可能是你初始化设置的问题 ，你需要在nuxt.config.js中去配置meta标签
